# Dos lugares por carta de la lotería CDMX.
# (num, nombre, lat, lng, radio_m, pista, como_llegar, resena, revisar)
# revisar=True  -> el punto es una propuesta floja y Javi tiene que decidirlo.
L = [
# 1 Los Padres
(1,"Antiguo Colegio de San Ildefonso",19.4363,-99.1306,90,
 "Un mural donde dos desnudos se dan la mano encima de un cuerpo caído.",
 "Justo Sierra 16, Centro. Metro Zócalo.",
 "Aquí Orozco pintó a la pareja de la que, dice el mural, salimos todos.",False),
(1,"Casa de la Malinche, Coyoacán",19.3497,-99.1617,80,
 "La casa que la leyenda le dio a la mujer que tradujo la Conquista.",
 "Higuera 57, esquina Vallarta, Coyoacán. Metro Viveros.",
 "Nadie sabe si vivió aquí, y sin embargo la plaza se llama como ella.",False),
# 2 La Latino
(2,"Torre Latinoamericana",19.4339,-99.1408,90,
 "Aguantó el temblor que tiró a los edificios nuevos.",
 "Eje Central esquina Madero. Metro Bellas Artes.",
 "Se construyó sobre el lodo de un lago y por eso sigue de pie.",False),
(2,"Alameda Central, lado oriente",19.4352,-99.1436,110,
 "Desde el parque más viejo de América se ve entera.",
 "Alameda Central, frente a Bellas Artes. Metro Bellas Artes.",
 "El mejor lugar para mirarla no es arriba: es desde abajo, entre los árboles.",False),
# 3 La Piedra del Sol
(3,"Museo Nacional de Antropología",19.4260,-99.1863,140,
 "El disco que todos llaman calendario y no lo es.",
 "Paseo de la Reforma s/n, Chapultepec. Metro Auditorio.",
 "Pesa veinticuatro toneladas y estuvo doscientos años enterrada bajo el Zócalo.",False),
(3,"Zócalo, donde apareció",19.4326,-99.1332,130,
 "Bajo esta plancha estuvo escondida hasta 1790.",
 "Plaza de la Constitución. Metro Zócalo.",
 "La encontraron unos albañiles arreglando la plaza y cambió lo que México creía de sí mismo.",False),
# 5 El Ángel
(5,"Monumento a la Independencia",19.4270,-99.1677,100,
 "No es un ángel. Es una victoria, y tiene alas.",
 "Reforma esquina Florencia. Metro Insurgentes.",
 "Se cayó entera en 1957 y la cabeza rodó por Reforma.",False),
(5,"Glorieta de la Palma",19.4288,-99.1710,90,
 "La glorieta vecina, donde Reforma cambia de ánimo.",
 "Paseo de la Reforma esquina Río Rhin.",
 "La palma que estuvo aquí un siglo se murió en 2022 y la ciudad le hizo funeral.",False),
# 6 La Catedral
(6,"Catedral Metropolitana",19.4341,-99.1331,100,
 "Se hundió tanto que tuvieron que levantarla por dentro.",
 "Plaza de la Constitución. Metro Zócalo.",
 "Tardó 240 años en terminarse y se construyó con las piedras del templo que tiró.",False),
(6,"Plaza de Santo Domingo",19.4372,-99.1339,90,
 "La otra plaza con iglesia, donde todavía escriben cartas a máquina.",
 "República de Cuba y Brasil, Centro. Metro Allende.",
 "Bajo los portales llevan siglos escribiendo lo que otros no saben escribir.",False),
# 7 El Huey Teocalli
(7,"Templo Mayor",19.4348,-99.1315,100,
 "Apareció cuando unos electricistas cavaron por equivocación.",
 "Seminario 8, Centro. Metro Zócalo.",
 "Siete templos, uno dentro de otro, como muñecas rusas de piedra.",False),
(7,"Tlatelolco, Plaza de las Tres Culturas",19.4513,-99.1378,130,
 "Tres tiempos de la ciudad en una sola plancha.",
 "Eje Central y Flores Magón. Metro Tlatelolco.",
 "Aquí se acabó la resistencia mexica, y la placa lo dice sin rodeos.",False),
# 8 La Llave
(8,"Arena México",19.4232,-99.1533,90,
 "La catedral de la lucha libre.",
 "Dr. Lavista 189, Doctores. Metro Cuauhtémoc.",
 "Viernes de función desde 1956, y la máscara sigue valiendo más que el título.",False),
(8,"Arena Coliseo",19.4391,-99.1355,80,
 "La arena chica del Centro, la que vino antes.",
 "República de Perú 77, Centro. Metro Lagunilla.",
 "Aquí empezó todo, cuando la lucha todavía cabía en un barrio.",False),
# 9 El Olímpico Universitario
(9,"Estadio Olímpico Universitario",19.3320,-99.1846,140,
 "Un cráter con un mural de Rivera en la entrada.",
 "Insurgentes Sur s/n, Ciudad Universitaria. Metrobús CU.",
 "Se hizo con la lava del Xitle y en 1968 vio correr al mundo entero.",False),
(9,"Espacio Escultórico, Ciudad Universitaria",19.3165,-99.1795,120,
 "Un anillo de piedra sobre lava, en medio del pedregal.",
 "Circuito Escultórico, CU. Metrobús CCU.",
 "Sesenta y cuatro prismas alrededor de la lava que quedó como estaba.",False),
# 10 La Catrina
(10,"Museo Mural Diego Rivera",19.4361,-99.1479,80,
 "Está en el mural, del brazo de quien la dibujó.",
 "Balderas y Colón, junto a la Alameda. Metro Hidalgo.",
 "Rivera la puso al centro del paseo dominical y le dio boa de plumas.",False),
(10,"Museo Nacional de la Estampa",19.4365,-99.1465,80,
 "Donde se guardan las planchas de quien la inventó.",
 "Av. Hidalgo 39, Plaza de la Santa Veracruz. Metro Bellas Artes.",
 "Posada la grabó como burla a las que renegaban de ser indias.",False),
# 11 El Mariachi
(11,"Plaza Garibaldi",19.4407,-99.1392,110,
 "Aquí se compran las canciones por pieza.",
 "Eje Central y Honduras. Metro Garibaldi.",
 "Llevan desde los años veinte parados en la misma esquina, esperando.",False),
(11,"Salón Tenampa",19.4409,-99.1387,60,
 "La cantina donde empezó la costumbre.",
 "Plaza Garibaldi 12. Metro Garibaldi.",
 "Abrió en 1925 y trajo a los primeros mariachis de Cocula.",False),
# 12 Los de Pastor
(12,"El Huequito, Bolívar",19.4316,-99.1400,70,
 "Un local angosto donde el trompo lleva girando desde 1959.",
 "Bolívar 58, Centro. Metro San Juan de Letrán.",
 "Los libaneses trajeron el shawarma y aquí se volvió pastor.",False),
(12,"El Tizoncito, Condesa",19.4118,-99.1745,70,
 "La Condesa también tiene su trompo con fama.",
 "Tamaulipas 122, Condesa. Metro Patriotismo.",
 "Se pelean el título de haber inventado el pastor en la ciudad.",False),
# 13 El Metro
(13,"Metro Pino Suárez",19.4258,-99.1328,90,
 "Hay una pirámide dentro de una estación.",
 "Estación Pino Suárez, líneas 1 y 2.",
 "Al excavar encontraron un templo a Ehécatl y lo dejaron ahí, entre los torniquetes.",False),
(13,"Metro Bellas Artes",19.4363,-99.1418,90,
 "El pasillo largo donde siempre hay alguien tocando.",
 "Estación Bellas Artes, líneas 2 y 8.",
 "Cada estación tiene un dibujo en vez de nombre, para quien no sabe leer.",False),
# 14 El Palacio
(14,"Palacio de Bellas Artes",19.4352,-99.1413,100,
 "Mármol italiano encima del lodo de un lago.",
 "Av. Juárez y Eje Central. Metro Bellas Artes.",
 "Empezó afrancesado y acabó art déco, porque la Revolución lo dejó a medias.",False),
(14,"Palacio Postal",19.4359,-99.1400,80,
 "El otro palacio de la esquina, donde se echan las cartas.",
 "Tacuba 1, Centro. Metro Bellas Artes.",
 "El mismo arquitecto, el mismo año, y sigue funcionando como correo.",False),
# 15 La Madre
(15,"Basílica de Guadalupe",19.4845,-99.1177,140,
 "Adonde llegan de rodillas los últimos metros.",
 "Plaza de las Américas 1, Villa de Guadalupe. Metro La Villa.",
 "El cerro ya era de una diosa madre antes de que llegara la otra.",False),
(15,"Cerro del Tepeyac",19.4862,-99.1170,110,
 "Arriba del cerro, donde estaba el templo viejo.",
 "Capilla del Cerrito, Villa de Guadalupe. Metro La Villa.",
 "Aquí se veneraba a Tonantzin, 'nuestra madrecita', mucho antes de 1531.",False),
# 16 La Mayáhuel
(16,"Sala Mexica, Museo Nacional de Antropología",19.4260,-99.1863,140,
 "La diosa de los cuatrocientos pechos.",
 "Paseo de la Reforma s/n, Chapultepec. Metro Auditorio.",
 "De sus huesos brotó el primer maguey, dice el mito.",False),
(16,"Pulquería Las Duelistas",19.4310,-99.1444,60,
 "Donde se sigue bebiendo lo que ella amamanta.",
 "Aranda 30, Centro. Metro Salto del Agua.",
 "Los murales de la pared cuentan el mismo mito que la carta.",False),
# 17 Los Centzon Totochtin
(17,"Sala Mexica, Museo Nacional de Antropología",19.4261,-99.1861,140,
 "Cuatrocientos conejos, uno por cada forma de estar borracho.",
 "Paseo de la Reforma s/n, Chapultepec. Metro Auditorio.",
 "Eran los hijos de Mayáhuel y cada uno traía su propia borrachera.",False),
(17,"Pulquería La Hermosa Hortensia",19.4410,-99.1387,60,
 "En Garibaldi, donde los conejos siguen sueltos.",
 "Plaza Garibaldi 4. Metro Garibaldi.",
 "Lleva desde 1935 sirviendo curados en la misma esquina.",False),
# 18 El Árbol de las Maravillas
(18,"Jardín Botánico, Ciudad Universitaria",19.3195,-99.1925,120,
 "El agave que daba techo, aguja, hilo, papel y bebida.",
 "Circuito Zona Deportiva, CU. Metrobús CCU.",
 "La colección de agaves más completa del país está aquí.",True),
(18,"Pulquería Las Duelistas",19.4311,-99.1443,60,
 "El final del árbol, servido en jarro.",
 "Aranda 30, Centro. Metro Salto del Agua.",
 "De una sola planta salía la casa entera: eso es un árbol de maravillas.",False),
# 19 El Alebrije
(19,"Museo de Arte Popular",19.4329,-99.1462,90,
 "De aquí sale el desfile de monstruos cada octubre.",
 "Revillagigedo 11, Centro. Metro Juárez.",
 "Pedro Linares los soñó con fiebre y despertó gritando la palabra.",False),
(19,"Museo Nacional de Culturas Populares, Coyoacán",19.3498,-99.1618,90,
 "La otra casa de lo que se hace a mano.",
 "Av. Hidalgo 289, Coyoacán. Metro Viveros.",
 "Aquí el alebrije convive con el resto de lo que inventa la gente.",False),
# 20 El Pepe
(20,"Casa Pepe, Centro Histórico",19.4326,-99.1450,70,
 "Donde empieza y acaba tu día en esta ciudad.",
 "Centro Histórico, CDMX.",
 "El hostal que se propuso enseñar cómo se es mexicano.",True),
(20,"Ateneo de Virreyes",19.4283,-99.1382,70,
 "Izazaga 8, primer piso: cine, coworking y escenario.",
 "José María Izazaga 8, piso 1, Centro Histórico. Metro Isabel la Católica.",
 "La casa donde el Grupo junta a los que trabajan, los que ven cine y los que se quedan.",True),
# 21 La Diana
(21,"Fuente de la Diana Cazadora",19.4258,-99.1727,90,
 "La flecha apunta a un cielo que ya no se ve.",
 "Reforma y Sevilla. Metro Sevilla.",
 "La vistieron con un taparrabos de bronce durante quince años por decencia.",False),
(21,"Bosque de Chapultepec, entrada Reforma",19.4235,-99.1770,110,
 "A dos pasos, donde el bosque empieza.",
 "Paseo de la Reforma y Lieja. Metro Chapultepec.",
 "Miraba hacia el bosque porque de ahí venía la caza.",True),
# 22 La Antonieta
(22,"Palacio de Bellas Artes",19.4353,-99.1411,100,
 "Puso su herencia en un teatro y en una orquesta.",
 "Av. Juárez y Eje Central. Metro Bellas Artes.",
 "Pagó la Orquesta Sinfónica Mexicana con el dinero de su padre.",False),
(22,"Monumento a la Revolución",19.4363,-99.1548,120,
 "Su padre levantó lo que iba a ser un palacio y acabó siendo esto.",
 "Plaza de la República. Metro Revolución.",
 "Antonio Rivas Mercado lo diseñó como Palacio Legislativo; quedó en cúpula.",False),
# 23 Los Filósofos
(23,"Facultad de Filosofía y Letras, UNAM",19.3266,-99.1866,120,
 "Donde se preguntaron si existe algo que sea ser mexicano.",
 "Circuito Interior s/n, CU. Metrobús CU.",
 "El grupo Hiperión discutió aquí si había una manera mexicana de estar en el mundo.",False),
(23,"El Colegio Nacional",19.4345,-99.1344,80,
 "La casa de los que piensan en voz alta y gratis.",
 "Donceles 104, Centro. Metro Allende.",
 "Sus conferencias llevan desde 1943 siendo abiertas para cualquiera.",False),
# 24 Los Historiadores
(24,"Museo del Templo Mayor",19.4351,-99.1313,90,
 "Quien lo excavó pasó aquí cuarenta años.",
 "Seminario 8, Centro. Metro Zócalo.",
 "Eduardo Matos Moctezuma dirigió la excavación que cambió el Centro.",False),
(24,"Biblioteca Nacional, Ciudad Universitaria",19.3195,-99.1867,110,
 "Donde están los libros que ellos leyeron para escribir los suyos.",
 "Circuito Mario de la Cueva, CU. Metrobús CCU.",
 "León-Portilla tradujo aquí lo que los vencidos alcanzaron a escribir.",True),
# 25 El Castillo
(25,"Castillo de Chapultepec",19.4204,-99.1817,140,
 "El único castillo de América donde vivió un emperador.",
 "Bosque de Chapultepec, 1a sección. Metro Chapultepec.",
 "Maximiliano mandó hacer Reforma sólo para llegar al trabajo desde aquí.",False),
(25,"Altar a la Patria, Niños Héroes",19.4224,-99.1826,100,
 "Seis columnas por seis muchachos.",
 "Bosque de Chapultepec, entrada principal. Metro Chapultepec.",
 "En 1847 defendieron el cerro contra el ejército que venía del norte.",False),
# 26 El Organillero
(26,"Plaza de la Constitución",19.4330,-99.1336,120,
 "El uniforme caqui y la manivela que no para.",
 "Zócalo. Metro Zócalo.",
 "Los organillos son alemanes, de hace más de un siglo, y suenan desafinados a propósito.",False),
(26,"Alameda Central",19.4356,-99.1450,120,
 "En el parque también se les oye.",
 "Alameda Central. Metro Hidalgo.",
 "Quedan menos de setecientos organillos y casi ninguno taller que los arregle.",False),
# 27 La Chinampa
(27,"Chinampas de San Gregorio Atlapulco",19.2607,-99.0800,150,
 "Huertos flotando sobre el agua desde antes de la Conquista.",
 "San Gregorio Atlapulco, Xochimilco.",
 "Siguen dando verdura para la ciudad, con la misma técnica de hace seiscientos años.",True),
(27,"Embarcadero Cuemanco",19.2870,-99.1010,130,
 "Desde aquí salen las trajineras a la zona chinampera.",
 "Periférico y Canal de Cuemanco, Xochimilco.",
 "La UNESCO metió a Xochimilco en su lista precisamente por esto.",False),
# 28 La Trajinera
(28,"Embarcadero Nuevo Nativitas",19.2630,-99.1050,130,
 "Barcas con nombre de mujer y arcos de flores.",
 "Nuevo Nativitas, Xochimilco. Tren Ligero Xochimilco.",
 "Antes cargaban flores y verdura; ahora cargan fiestas.",False),
(28,"Embarcadero Belem de las Flores",19.2638,-99.1085,110,
 "El muelle chico, donde hay menos ruido.",
 "Belem, Xochimilco.",
 "El nombre de cada trajinera se pinta a mano en el arco.",True),
# 29 El Ajolote
(29,"Cuemanco, canal del ajolote",19.2842,-99.1040,120,
 "Se regenera entero y nunca se hace adulto.",
 "Canal de Cuemanco, Xochimilco.",
 "Quedan menos de cien por kilómetro cuadrado en el único lugar del mundo donde vive.",False),
(29,"Museo Universum, Ciudad Universitaria",19.3220,-99.1790,110,
 "Donde lo tienen vivo para que lo veas de cerca.",
 "Circuito Cultural, CU. Metrobús CCU.",
 "Axolotl viene de Xólotl, el dios que se transformó para no morir.",True),
# 30 El Kalimán
(30,"Puesto de revistas, Eje Central",19.4353,-99.1409,90,
 "El héroe que venía cada semana en papel.",
 "Eje Central, frente a Bellas Artes. Metro Bellas Artes.",
 "Su historieta vendió millones y su radionovela paraba al país.",True),
(30,"Lagunilla, tianguis de coleccionistas",19.4437,-99.1372,110,
 "Los domingos aparecen los números viejos.",
 "Comonfort y Rayón, Lagunilla. Metro Garibaldi.",
 "'Serenidad y paciencia', decía, y la gente lo repite sin saber de dónde.",False),
# 31 El Tata
(31,"Mercado de San Juan",19.4304,-99.1428,90,
 "El que corta el trompo sin mirar el cuchillo.",
 "Ernesto Pugibet 21, Centro. Metro San Juan de Letrán.",
 "El taquero de trompo es un oficio de años y de muñeca.",True),
(31,"El Huequito, Bolívar",19.4315,-99.1401,60,
 "Detrás del trompo, el mismo señor desde hace décadas.",
 "Bolívar 58, Centro. Metro San Juan de Letrán.",
 "Le dicen tata al que lleva tanto que ya es de la familia.",True),
# 32 Las Ficheras
(32,"Teatro Blanquita",19.4396,-99.1408,80,
 "El escenario de la carpa y el cabaret.",
 "Eje Central 16, Centro. Metro Garibaldi.",
 "Por aquí pasó todo lo que el cine de ficheras después copió.",True),
(32,"Salón Los Ángeles",19.4530,-99.1520,90,
 "Quien no conoce Los Ángeles, no conoce México.",
 "Lerdo 206, Guerrero. Metro Tlatelolco.",
 "Lleva desde 1937 con la misma pista de danzón.",False),
# 33 El Tlachiquero
(33,"Pulquería Las Duelistas",19.4309,-99.1445,60,
 "El que raspa el maguey y chupa el aguamiel con un acocote.",
 "Aranda 30, Centro. Metro Salto del Agua.",
 "Un maguey tarda diez años en estar listo para que lo raspen.",False),
(33,"Jardín Botánico, Ciudad Universitaria",19.3196,-99.1924,120,
 "Aquí están los magueyes que él raspaba.",
 "Circuito Zona Deportiva, CU. Metrobús CCU.",
 "El oficio casi se acaba cuando llegó la cerveza.",True),
# 34 El Pulque
(34,"Pulquería La Hermosa Hortensia",19.4411,-99.1386,60,
 "Blanco, espeso, y con nombre de curado.",
 "Plaza Garibaldi 4. Metro Garibaldi.",
 "Fue la bebida ritual de los mexicas y sólo la bebían los viejos.",False),
(34,"Pulquería La Risa",19.4312,-99.1400,60,
 "La más vieja que sigue abierta en el Centro.",
 "Mesones 71, Centro. Metro Isabel la Católica.",
 "Abrió en 1903 y no ha cambiado el mostrador.",False),
# 35 La Licuachela
(35,"Tepito, calle Aztecas",19.4438,-99.1268,100,
 "Una michelada servida en vaso de licuadora.",
 "Aztecas, Tepito. Metro Lagunilla.",
 "Nació aquí, por el tamaño y por la prisa.",True),
(35,"Mercado de Tepito",19.4452,-99.1284,100,
 "En el mercado se pide por litros.",
 "Tepito, Cuauhtémoc. Metro Tepito.",
 "El barrio bravo inventó media jerga de la ciudad, y también esto.",True),
# 36 El Quetzalcóatl
(36,"Templo de Quetzalcóatl, Teotihuacan",19.6891,-98.8366,150,
 "Cabezas de serpiente emplumada saliendo del muro.",
 "Zona Arqueológica de Teotihuacan, Estado de México.",
 "La Ciudadela guarda el templo más antiguo dedicado a la serpiente.",False),
(36,"Sala Teotihuacan, Museo Nacional de Antropología",19.4259,-99.1864,140,
 "La réplica del templo, dentro del museo.",
 "Paseo de la Reforma s/n, Chapultepec. Metro Auditorio.",
 "Quetzalcóatl es viento, estrella de la mañana y el que se fue prometiendo volver.",False),
# 37 El Octavio Paz
(37,"El Colegio Nacional",19.4346,-99.1343,80,
 "Miembro desde los cincuenta, y venía a dar clase.",
 "Donceles 104, Centro. Metro Allende.",
 "Escribió El laberinto de la soledad estando lejos de aquí.",False),
(37,"Biblioteca Vasconcelos",19.4462,-99.1497,120,
 "La biblioteca que flota, donde están todos sus libros.",
 "Eje 1 Norte, junto a Buenavista. Metro Revolución.",
 "Ganó el Nobel en 1990 y dijo que la poesía era la otra voz.",True),
# 38 El Siqueiros
(38,"Polyforum Cultural Siqueiros",19.3925,-99.1758,110,
 "Un mural que te envuelve por dentro y por fuera.",
 "Insurgentes Sur 701, Nápoles. Metrobús Poliforum.",
 "La marcha de la humanidad: el mural más grande que se ha pintado.",False),
(38,"Sala de Arte Público Siqueiros",19.4290,-99.1749,80,
 "La casa donde vivió y pintó sus últimos años.",
 "Tres Picos 29, Polanco. Metro Auditorio.",
 "La donó al pueblo de México veinticinco días antes de morir.",False),
# 39 El Arqui
(39,"Casa Luis Barragán",19.4116,-99.1868,70,
 "Muros de color y luz medida, detrás de una fachada gris.",
 "Gral. Francisco Ramírez 12-14, Ampliación Daniel Garza. Metro Constituyentes.",
 "Es la única casa particular de América en la lista de la UNESCO.",False),
(39,"Torres de Satélite",19.5108,-99.2358,110,
 "Cinco prismas de colores en medio de la carretera.",
 "Periférico Norte, Ciudad Satélite, Naucalpan.",
 "Las hizo con Mathias Goeritz en 1958 para que se vieran desde el coche.",False),
# 40 El Rivera
(40,"Palacio Nacional, murales de la escalera",19.4327,-99.1313,110,
 "Pintó toda la historia de México en una escalera.",
 "Plaza de la Constitución. Metro Zócalo.",
 "Tardó seis años y no dejó fuera a casi nadie.",False),
(40,"Museo Casa Estudio Diego Rivera y Frida Kahlo",19.3466,-99.1930,90,
 "Dos casas unidas por un puente, una rosa y una azul.",
 "Diego Rivera y Altavista, San Ángel Inn.",
 "Juan O'Gorman se las hizo en 1932: la primera casa funcionalista de América Latina.",False),
# 41 Las Dos Fridas
(41,"Museo Frida Kahlo, Casa Azul",19.3552,-99.1624,90,
 "La casa donde nació y donde murió, del mismo color.",
 "Londres 247, Coyoacán. Metro Coyoacán.",
 "Pintó Las dos Fridas el año en que se divorció de Rivera.",False),
(41,"Museo de Arte Moderno",19.4249,-99.1823,100,
 "Donde cuelgan los cuadros que no se quedaron en su casa.",
 "Paseo de la Reforma y Gandhi, Chapultepec. Metro Chapultepec.",
 "Aquí está Las dos Fridas, con el corazón abierto y la vena cortada.",False),
# 42 El Tianguis
(42,"Mercado de La Merced",19.4249,-99.1246,130,
 "El mercado más grande, donde se surte la ciudad entera.",
 "Rosario y Anillo de Circunvalación. Metro Merced.",
 "Tianguis viene de tianquiztli: así se llamaba el de Tlatelolco.",False),
(42,"Tianguis de La Lagunilla, domingo",19.4437,-99.1373,120,
 "Los domingos aparece y el lunes ya no está.",
 "Comonfort y Rayón. Metro Garibaldi.",
 "El tianguis es más viejo que la tienda: se pone, se levanta y se va.",False),
# 43 El Trotski
(43,"Museo Casa de León Trotsky",19.3577,-99.1590,80,
 "Los muros altos no le alcanzaron.",
 "Río Churubusco 410, Coyoacán. Metro Coyoacán.",
 "Lo mataron aquí en 1940, con un piolet, en su escritorio.",False),
(43,"Casa Azul, Coyoacán",19.3553,-99.1623,90,
 "Antes de la casa fortificada, vivió en la azul.",
 "Londres 247, Coyoacán. Metro Coyoacán.",
 "Llegó a México en 1937 porque Rivera se lo pidió al presidente Cárdenas.",False),
# 44 El Divo de Juárez
(44,"Palacio de Bellas Artes",19.4351,-99.1414,100,
 "Preguntó si querían que siguiera cantando y no paró.",
 "Av. Juárez y Eje Central. Metro Bellas Artes.",
 "Cantó aquí en 1990 con orquesta, y le tomó el escenario a la ópera.",False),
(44,"Plaza Garibaldi",19.4405,-99.1394,110,
 "Aquí sus canciones se piden más que las de nadie.",
 "Eje Central y Honduras. Metro Garibaldi.",
 "Escribió más de mil ochocientas canciones y no sabía leer música.",False),
# 45 El Pepesero
(45,"Paradero Indios Verdes",19.4948,-99.1196,140,
 "El microbús que arranca antes de que subas.",
 "Paradero Indios Verdes. Metro Indios Verdes.",
 "Se llama pesero porque el viaje costaba un peso.",False),
(45,"Paradero Metro Chapultepec",19.4205,-99.1766,110,
 "Otro nido de rutas, con letreros en el parabrisas.",
 "Paradero Chapultepec. Metro Chapultepec.",
 "Los letreros del parabrisas son un alfabeto que sólo entiende quien vive aquí.",False),
# 46 El Cine de Oro
(46,"Cine Ópera",19.4400,-99.1608,90,
 "Una sala enorme y cerrada, con el techo caído.",
 "Serapio Rendón 9, San Rafael. Metro San Cosme.",
 "Se apagó en 1998 y sigue ahí, esperando que alguien la encienda.",False),
(46,"Cineteca Nacional",19.3640,-99.1637,100,
 "Donde todavía se proyectan las películas de entonces.",
 "México Coyoacán 389, Xoco. Metro Coyoacán.",
 "Se incendió en 1982 y perdió miles de rollos; se volvió a levantar.",False),
# 47 Los Poetas Novohispanos
(47,"Claustro de Sor Juana",19.4269,-99.1364,90,
 "El convento donde escribió y donde le quitaron los libros.",
 "Izazaga 92, Centro. Metro Isabel la Católica.",
 "Tenía cuatro mil volúmenes y tuvo que venderlos todos.",False),
(47,"Templo de San Jerónimo",19.4267,-99.1367,70,
 "Aquí está enterrada.",
 "Izazaga y San Jerónimo, Centro. Metro Isabel la Católica.",
 "Murió cuidando a sus hermanas en una peste, en 1695.",False),
# 48 La Periodista
(48,"Tlatelolco, Plaza de las Tres Culturas",19.4515,-99.1376,130,
 "Recogió las voces de la noche que nadie quiso contar.",
 "Eje Central y Flores Magón. Metro Tlatelolco.",
 "La noche de Tlatelolco se hizo con testimonios, no con opiniones.",False),
(48,"Casa Museo Elena Poniatowska",19.3405,-99.1710,80,
 "Su casa, convertida en archivo abierto.",
 "Benito Juárez 27, Chimalistac, Álvaro Obregón.",
 "Donó su archivo y su casa para que se pudieran consultar.",True),
# 49 La Jacaranda
(49,"Parque México, Condesa",19.4124,-99.1713,110,
 "En marzo la calle se pone morada.",
 "Av. México, Hipódromo Condesa. Metro Chilpancingo.",
 "Las trajo un jardinero japonés, Tatsugoro Matsumoto, porque aquí no dan cerezos.",False),
(49,"Ciudad Universitaria, Las Islas",19.3330,-99.1870,130,
 "El campus entero florece al mismo tiempo.",
 "Las Islas, CU. Metrobús CU.",
 "Florecen antes cada año, y eso es lo que están midiendo los biólogos.",False),
# 50 La Isla
(50,"Zócalo, corazón de la isla",19.4328,-99.1334,120,
 "Todo esto era agua, y esto era el centro.",
 "Plaza de la Constitución. Metro Zócalo.",
 "La ciudad se hizo sobre un islote y el lago sigue debajo, hundiéndola.",False),
(50,"Templo Mayor, orilla del recinto",19.4350,-99.1312,90,
 "Desde aquí salían las calzadas al resto del lago.",
 "Seminario 8, Centro. Metro Zócalo.",
 "Tres calzadas la unían a tierra firme, y una de ellas era Tacuba.",False),
# 52 La Fundación
(52,"Zócalo, asta bandera",19.4325,-99.1332,110,
 "El águila sobre el nopal está en el centro de todo.",
 "Plaza de la Constitución. Metro Zócalo.",
 "Aquí vieron la señal, según la historia que se contó después.",False),
(52,"Museo Nacional de Antropología, sala Mexica",19.4262,-99.1862,140,
 "La piedra donde quedó tallada la señal.",
 "Paseo de la Reforma s/n, Chapultepec. Metro Auditorio.",
 "El Teocalli de la Guerra Sagrada trae el nopal y el águila, en piedra.",False),
# 53 El Códice Boturini
(53,"Biblioteca Nacional de Antropología e Historia",19.4267,-99.1858,120,
 "Una tira de papel amate con las huellas del camino.",
 "Museo Nacional de Antropología, Chapultepec. Metro Auditorio.",
 "Se llama Tira de la Peregrinación y cuenta el viaje desde Aztlán.",False),
(53,"Museo Nacional de Antropología, sala Mexica",19.4260,-99.1860,140,
 "La réplica que sí se puede ver de cerca.",
 "Paseo de la Reforma s/n, Chapultepec. Metro Auditorio.",
 "Boturini la coleccionó y el virrey se la quitó toda.",False),
# 54 La Luna
(54,"Museo del Templo Mayor",19.4352,-99.1312,90,
 "La diosa desmembrada al pie de la escalera.",
 "Seminario 8, Centro. Metro Zócalo.",
 "El disco de Coyolxauhqui apareció en 1978 y por él se excavó todo.",False),
(54,"Pirámide de la Luna, Teotihuacan",19.6995,-98.8438,150,
 "La otra pirámide, la del fondo de la calzada.",
 "Zona Arqueológica de Teotihuacan, Estado de México.",
 "Le dijeron de la Luna los mexicas, siglos después de que la ciudad se vaciara.",False),
]
