/* El conmutador ES/EN de APePe: se cuelga junto a la campanita.
 *
 * Vive en un archivo aparte por lo mismo que notis.js: el botón tiene que salir
 * igual en todas las pantallas del huésped y no queremos copiarlo seis veces.
 *
 * La llave es `apepe_lang`, que es la que ya leía notis.js. De paso se escribe
 * `apepe_ckin_lang`, que es la que mira el check-in, para que no queden dos
 * idiomas distintos en la misma sesión. Y se recarga con `?lang=` en la liga
 * porque así es como sinc-i18n.js resuelve el idioma del contenido traducido.
 */
(function () {
  'use strict';
  if (window.__apepeIdioma) return;
  window.__apepeIdioma = true;

  function lee() {
    try {
      var q = new URLSearchParams(location.search).get('lang');
      if (q === 'en' || q === 'es') return q;
      var g = localStorage.getItem('apepe_lang');
      if (g === 'en' || g === 'es') return g;
    } catch (_) {}
    // Sin preferencia guardada: lo que traiga el navegador, y por omisión español.
    try { return (navigator.language || '').slice(0, 2) === 'en' ? 'en' : 'es'; } catch (_) {}
    return 'es';
  }

  function pon(l) {
    try {
      localStorage.setItem('apepe_lang', l);
      localStorage.setItem('apepe_ckin_lang', l);
    } catch (_) {}
    try { document.documentElement.lang = l; } catch (_) {}
    var u = new URL(location.href);
    u.searchParams.set('lang', l);
    location.replace(u.toString());
  }


  /* EL DICCIONARIO.
     La llave es la propia frase en español, como en sinc-i18n.js. Suena raro y
     tiene dos ventajas que valen más que la elegancia: no hay que inventar
     nombres de llave (ni equivocarse al escribirlos), y a una frase sin
     traducir le sale el español, nunca un hueco. Los nombres propios —Pepe GO!,
     La Cósmica, PepeQuiz, Vnums— no se traducen a propósito. */
  var DIC = {
    'y': 'and',
    'Yo': 'Me',
    'Hoy': 'Today',
    'Oro': 'Gold',
    'Red': 'Network',
    'abr': 'apr',
    'ago': 'aug',
    'dic': 'dec',
    'ene': 'jan',
    'feb': 'feb',
    'jul': 'jul',
    'jun': 'jun',
    'mar': 'mar',
    'may': 'may',
    'nov': 'nov',
    'oct': 'oct',
    'sep': 'sep',
    'Cama': 'Bed',
    'Guía': 'Guide',
    'Mapa': 'Map',
    'Menú': 'Menu',
    'Ahora': 'Now',
    'Antes': 'Before',
    'Dónde': 'Where',
    'Pieza': 'Piece',
    'Suite': 'Suite',
    'Todas': 'All',
    'Usada': 'Used',
    'noche': 'night',
    '/noche': '/night',
    'Avisos': 'Notifications',
    'Caducó': 'Expired',
    'Cerrar': 'Close',
    'Cocina': 'Kitchen',
    'Copiar': 'Copy',
    'Cuándo': 'When',
    'Enviar': 'Send',
    'Ganas:': 'You get:',
    'Gratis': 'Free',
    'Inicio': 'Home',
    'Listo.': 'Done.',
    'Madera': 'Wood',
    'Mañana': 'Tomorrow',
    'Mejora': 'Upgrade',
    'Noches': 'Nights',
    'Pagada': 'Paid',
    'Pista:': 'Clue:',
    'Promos': 'Deals',
    'Puntos': 'Points',
    'Salida': 'Check-out',
    'Ver QR': 'See QR',
    'Volver': 'Back',
    'noches': 'nights',
    'Empezar': 'Start',
    'Entrada': 'Check-in',
    'Firmado': 'Signed',
    'Jugar ▸': 'Play ▸',
    'Lo tuyo': 'Your stuff',
    'Ni una…': 'Not one…',
    'Ocultar': 'Hide',
    'Ofrecer': 'Offer',
    'Persona': 'Guest',
    'Reserva': 'Booking',
    '🗺️ Mapa': '🗺️ Map',
    '24 horas': '24 hours',
    'Ahora no': 'Not now',
    'Desayuno': 'Breakfast',
    'La tabla': 'The board',
    'Mirando…': 'Having a look…',
    'Nacional': 'National',
    'Personas': 'Guests',
    'Sales el': 'You leave on',
    'de extra': 'extra',
    'un canal': 'another channel',
    '⚔️ Retar': '⚔️ Challenge',
    'Cancelada': 'Cancelled',
    'Cargando…': 'Loading…',
    'Confirmar': 'Confirm',
    'Coworking': 'Coworking area',
    'Dirección': 'Address',
    'Firmando…': 'Signing…',
    'Hola Pepe': 'Hi Pepe',
    'Hola, {n}': 'Hi, {n}',
    'La ciudad': 'The city',
    'La semana': 'This week',
    'La tienda': 'The shop',
    'Sin fotos': 'No photos',
    'Tu cuarto': 'Your room',
    'Ver menos': 'See less',
    'Virreinal': 'Virreinal',
    'sin cargo': 'no charge',
    'sin fecha': 'no date',
    '{n} noche': '{n} night',
    '¡Ésa era!': 'That was it!',
    '⚔️ Retado': '⚔️ Challenged',
    '✨ Los dos': '✨ Both',
    '⤢ Ampliar': '⤢ Zoom',
    'Bienvenida': 'Welcome',
    'Cobrada el': 'Redeemed on',
    'Dormitorio': 'Dorm',
    'Habitación': 'Room',
    'Sala de TV': 'TV room',
    'Siguiente…': 'Next…',
    'Tu reserva': 'Your booking',
    'Tu upgrade': 'Your upgrade',
    'Tus cartas': 'Your cards',
    'Ver todo →': 'See it all →',
    'Voluntario': 'Volunteer',
    'al llegar.': 'for you when you arrive.',
    '{n} noches': '{n} nights',
    '¡Correcto!': 'Correct!',
    'Buscándola…': 'Looking for it…',
    'Cómo llegar': 'How to get there',
    'Experiencia': 'Experience',
    'Jugar ahora': 'Play now',
    'Preparando…': 'Getting it ready…',
    'Reembolsada': 'Refunded',
    'Siguiente ▸': 'Next ▸',
    'Tu estancia': 'Your stay',
    'Tus boletos': 'Your tickets',
    'Un momento…': 'One moment…',
    'Ver el mapa': 'See the map',
    'Ver qué hay': 'See what is on',
    'Ver todas →': 'See them all →',
    'sin mudarte': 'no move',
    '{n} lugares': '{n} places',
    '{n} persona': '{n} guest',
    '¿Lo aparto?': 'Shall I hold it?',
    '🎴 Pasaporte': '🎴 Passport',
    '7:00 – 22:00': '7:00 AM – 10:00 PM',
    'Borrar firma': 'Clear signature',
    'Calificando…': 'Scoring…',
    'Cocina común': 'Kitchen',
    'Experiencias': 'Experiences',
    'Hoy y mañana': 'Today and tomorrow',
    'Jugar otra ▸': 'Play again ▸',
    'Nueva salida': 'New check-out',
    'Pepe huésped': 'Pepe guest',
    'Solicitando…': 'Asking…',
    'Ya la usaste': 'Already used',
    'tu billetera': 'your wallet',
    '{n} personas': '{n} guests',
    '🎴 Tus cartas': '🎴 Your cards',
    '📍 Estoy aquí': '📍 I am here',
    '14:00 a 19:00': '14:00 to 19:00',
    'Mesoamericano': 'Mesoamerican',
    'Mi día / Guía': 'My day / Guide',
    'Respondió {c}': 'The server replied {c}',
    'Sé el primero': 'Be the first',
    'Tu habitación': 'Your room',
    '¿Dónde andas?': 'Where are you?',
    'Acepto y firmo': 'I accept and sign',
    'Check-in hecho': 'Checked in',
    'Dónde y cuándo': 'Where and when',
    'Lleva efectivo': 'Carry cash',
    'Pago pendiente': 'Payment pending',
    'Reservaste por': 'Booked through',
    'Tarifa directa': 'Direct rate',
    'Tus documentos': 'Your documents',
    'Ver descuentos': 'See the deals',
    'Ver mi reserva': 'See my booking',
    'Ver opciones ↓': 'See options ↓',
    'Ver tu upgrade': 'See your upgrade',
    '¿Qué hago hoy?': 'What should I do today?',
    'Aceptar el reto': 'Take the challenge',
    'Extra por noche': 'Extra per night',
    'Falta tu firma.': 'Your signature is missing.',
    'Guardar maletas': 'Storage',
    'Mira el resto →': 'See the rest →',
    'Por tu check-in': 'For checking in',
    'Quiero quedarme': 'I want to stay',
    'Te cambiamos a:': 'We move you to:',
    'Ver mi contrato': 'See my contract',
    'WiFi de la casa': 'House WiFi',
    'Ya nos dijiste:': 'You already told us:',
    'desde las 15:00': 'from 15:00',
    'desde las 23:00': 'from 23:00',
    'hasta las 12:00': 'until 12:00',
    'hasta las 22:00': 'until 10:00 PM',
    '¿Dónde duermes?': 'Where do you sleep?',
    '¿Te quedas más?': 'Staying longer?',
    'Caducó sin pagar': 'Expired unpaid',
    'El premio de hoy': 'Today\'s prize',
    'Estás en tu casa': 'Make yourself at home',
    'No se pudo retar': 'Could not send the challenge',
    'Ranking · cartas': 'Leaderboard · cards',
    'Recepción y sala': 'Front desk living room',
    'Salir a cazarlos': 'Go hunt them',
    'Te mudas de cama': 'You change beds',
    'Tu nueva reserva': 'Your new booking',
    'Ver experiencias': 'See experiences',
    'Ver mi pasaporte': 'See my passport',
    'Ver mis cartas ▸': 'See my cards ▸',
    'Aceptar el reto ▸': 'Take the challenge ▸',
    'Agotada por ahora': 'Sold out for now',
    'Firma con tu dedo': 'Sign with your finger',
    'Hacer el check-in': 'Check in',
    'Lo que ya es tuyo': 'What is already yours',
    'Lobby / recepción': 'Lobby / reception',
    'Mirando qué sale…': 'Checking what is on…',
    'Nada aquí todavía': 'Nothing here yet',
    'No. Era la verde.': 'Nope. It was the green one.',
    'Reservar otra vez': 'Book it again',
    'Terminar de pagar': 'Finish paying',
    'Total del upgrade': 'Upgrade total',
    'en el mismo sitio': 'same place',
    'foto próximamente': 'photo coming soon',
    '¿Te vas a quedar?': 'Are you staying?',
    'Apartando tu cama…': 'Holding your bed…',
    'Error de conexión.': 'Connection error.',
    'Habitación privada': 'Private room',
    'La casa por dentro': 'Facilities',
    'Mejora tu estancia': 'Upgrade your stay',
    'Pídela a tu cuarto': 'Bring it to my room',
    'Regalo del viernes': 'Friday gift',
    'Transporte público': 'Public transport',
    'Ver mi resultado ▸': 'See my score ▸',
    'Ver mi carta ▸': 'See my card ▸',
    /* Lo que ve el huésped según el momento de su reserva: antes de llegar,
       dentro, y cuando ya se fue. */
    'Mejora tu habitación': 'Upgrade your room',
    '¿Cuándo vuelves?': 'When are you back?',
    'Esta casa ya es un poco tuya.': 'This house is already a little bit yours.',
    'Tus estancias': 'Your stays',
    'Todo lo que te has quedado con nosotros.': 'Every time you have stayed with us.',
    'En total': 'All together',
    '{n} estancia': '{n} stay',
    '{n} estancias': '{n} stays',
    'Una estancia': 'One stay',
    'ahora': 'now',
    'Una noche en esta casa': 'One night in this house',
    '{n} noches en esta casa': '{n} nights in this house',
    'Tu 15% de siempre, ya aplicado aquí abajo. No tienes que escribirlo.': 'Your usual 15%, already applied below. You do not have to type it in.',
    'Elige tus fechas': 'Pick your dates',
    'Ver fechas y precios': 'See dates and prices',
    'No. Era «{r}».': 'Nope. It was “{r}”.',
    'No era ésa.': 'That was not it.',
    'Con tu 15% ya aplicado': 'With your 15% already applied',
    'Tu 15% de siempre, ya aplicado en la liga. No tienes que escribirlo.': 'Your usual 15%, already built into the link. You do not have to type it in.',
    'Reservas Casa Pepe': 'Casa Pepe bookings',
    'Si prefieres verlo en grande, ': 'Rather see it full size? ',
    'ábrelo aparte ↗': 'open it in its own tab ↗',
    'Eres socio de la casa': 'You are a partner of the house',
    'Reservas a tarifa de socio y la noche se carga a tu cuenta, sin pagar aquí. Dinos las fechas y te la dejamos hecha.': 'You book at the partner rate and the night goes to your account — nothing to pay here. Tell us the dates and we will set it up.',
    'Tu reserva de socio': 'Your partner booking',
    'El motor de socio está en camino. Mientras tanto, escríbenos y te la dejamos lista el mismo día.': 'The partner booking engine is on its way. In the meantime, write to us and we will have it ready the same day.',
    'Un momento…': 'One moment…',

    'consulta la semana': 'check the week',
    '¡Subiste de carta!': 'You levelled up your card!',
    'Cargando la tienda…': 'Opening the shop…',
    'Cargando preguntas…': 'Loading questions…',
    'De parte de la casa': 'On the house',
    'Descanso (silencio)': 'Quiet hours',
    'Horarios de la casa': 'House hours',
    'Intentarlo otra vez': 'Try again',
    'No se pudo procesar': 'We could not process it',
    'Pregunta {i} de {n}': 'Question {i} of {n}',
    'Se te fue el tiempo': 'Time ran out',
    'Total con SuperPepe': 'Total with SuperPepe',
    'Tu nueva habitación': 'Your new room',
    'Ver fotos y detalle': 'See photos and details',
    'la casa y su cocina': 'the house and its kitchen',
    'tu nueva habitación': 'your new room',
    '¿Quieres saber más?': 'Want to know more?',
    'Abriendo la vitrina…': 'Opening the shop…',
    'Avisarme al teléfono': 'Notify me on my phone',
    'Contraseña copiada ✓': 'Password copied ✓',
    'Enséñalo al reservar': 'Show it when you book',
    'Hecho por {artesana}': 'Made by {artesana}',
    'Hoy · reparte premio': 'Today · prize on the line',
    'La revancha es tuya.': 'The rematch is yours.',
    'No se pudo descargar': 'Could not download it',
    'Ofertas y descuentos': 'Offers and discounts',
    'Ranking de la semana': 'This week’s leaderboard',
    'Subir por {p} /noche': 'Move up for {p} /night',
    'Un personaje te reta': 'A character challenges you',
    '¿Cuántas noches más?': 'How many more nights?',
    '⬇ Descargar mi carta': '⬇ Download my card',
    'Búscalo en la ciudad.': 'Go find them out in the city.',
    'Centrado donde estás.': 'Centred on you.',
    'Contrato de hospedaje': 'Accommodation contract',
    'Escríbele a Don José…': 'Write to Don José…',
    'Karaoke, DJ y eventos': 'Karaoke, DJ and events',
    'No se pudo calificar.': 'We could not score it.',
    'Por ganar el PepeQuiz': 'For winning the PepeQuiz',
    'Regaderas compartidas': 'Shared showers',
    'Tienda en preparación': 'Shop on its way',
    'Tu coctel de cortesía': 'Your welcome cocktail',
    'Tócala para ver el QR': 'Tap it to see the QR',
    'Ver de dónde salieron': 'See where they came from',
    'Viendo qué hay libre…': 'Checking what is free…',
    'desayuno 7:00 – 11:00': 'breakfast 7:00 – 11:00 AM',
    'Bienvenido a Casa Pepe': 'Welcome to Casa Pepe',
    'Buscando tu ubicación…': 'Finding you…',
    'Cargando tus opciones…': 'Loading your options…',
    'Datos para el teléfono': 'Stay connected',
    'Enséñalo en la terraza': 'Show it at the terrace',
    'Preguntarle a Don José': 'Ask Don José',
    'Solicitar el descuento': 'Ask for the discount',
    'Ver el mapa completo →': 'See the whole map →',
    ', se pagan en recepción': ', paid at reception',
    'Desayuno, comida y cena': 'Breakfast, lunch and dinner',
    'Personaje por descubrir': 'Character still hidden',
    'Pregunta {n} de {total}': 'Question {n} of {total}',
    'Vitrina en preparación.': 'Shop on its way.',
    'Del aeropuerto o la TAPO': 'From the airport or TAPO',
    'Quinto piso · la terraza': 'Fifth floor · the terrace',
    'Ver el mapa de la ciudad': 'Open the city map',
    'ese reto ya no está vivo': 'that challenge is no longer live',
    'tu conserje en Casa Pepe': 'your concierge at Casa Pepe',
    'Ya tienes todo por aquí ✨': 'You have everything around here ✨',
    '¿Dónde te estás quedando?': 'Where are you staying?',
    '¿Sobre qué quieres jugar?': 'What do you want to play about?',
    'Abriendo las experiencias…': 'Opening the experiences…',
    'Confirmar tu cambio a {r}.': 'Confirm your move to {r}.',
    'Don José está escribiendo…': 'Don José is typing…',
    'No reconocemos tu reserva.': 'We do not recognise your booking.',
    'Todavía no lo tiene nadie.': 'Nobody has it yet.',
    'Ya la tenías igual o mejor': 'You already had it the same or better',
    '{n} se te fueron de tiempo': '{n} ran out of time',
    'Juegas como <b>{nombre}</b>': 'Playing as <b>{nombre}</b>',
    'No pudimos cargar la tienda': 'We could not load the shop',
    'No se pudo iniciar el reto.': 'We could not start the challenge.',
    'Un personaje te espera aquí': 'A character is waiting here',
    'todos los días 7:00 – 23:00': 'every day 7:00 – 23:00',
    '¿Cómo llego del aeropuerto?': 'How do I get here from the airport?',
    'Red abierta · sin contraseña': 'Open network · no password',
    'Ver las otras {n} opciones ▾': 'See the other {n} options ▾',
    'caza anécdotas por la ciudad': 'hunt down stories across the city',
    'piezas con alma, a tu cuarto': 'pieces with soul, to your room',
    'tu estancia es de {n} noches': 'your stay is {n} nights',
    'La red aún no está publicada.': 'The network is not up here yet.',
    'No se pudo cargar el ranking.': 'We could not load the leaderboard.',
    '🏆 Ver el ranking de la semana': '🏆 See this week’s leaderboard',
    'No pudimos cargar las salidas.': 'We could not load today’s departures.',
    'Estamos cerrando tu habitación…': 'We are locking in your room…',
    'Falló la conexión al calificar.': 'The connection dropped while scoring.',
    'Nada en esta colección todavía.': 'Nothing in this collection yet.',
    'Qué tiene que ver con un viaje.': 'What this has to do with travelling.',
    'Puedes repetirlo cuando quieras.': 'Play again whenever you like.',
    'Te esperamos con la llave lista.': 'We will have your key ready.',
    '📶 Conectarme desde este teléfono': '📶 Connect this phone',
    'Escanea el código para conectarte': 'Scan the code to connect',
    '⚔️ {rival} te ganó {sus} a {mis}.': '⚔️ {rival} beat you {sus} to {mis}.',
    'Te mandamos el detalle por correo.': 'We have emailed you the details.',
    'Tu teléfono no comparte ubicación.': 'Your phone does not share its location.',
    'Vas ganando con {n} puntos de hoy.': 'You are in front with {n} points today.',
    '✓ Estás a {n} m — ¡puedes retarlo!': '✓ You are {n} m away — go for it!',
    'No sueltas nada: no hiciste puntos.': 'You give up nothing: you scored no points.',
    'Son {m}, que se pagan en recepción.': 'It comes to {m}, paid at reception.',
    'lo puedes reclamar en La Cósmica de': 'is waiting for you at La Cósmica from',
    'Falló la conexión. Intenta de nuevo.': 'Connection failed. Try again.',
    'Lo que firmaste al hacer el check-in.': 'What you signed at check-in.',
    'No se pudo. Pregúntanos en recepción.': 'It did not work. Ask us at reception.',
    '¿En qué idioma quieres las preguntas?': 'What language do you want the questions in?',
    'Error de conexión. Inténtalo de nuevo.': 'Connection error. Try again.',
    'Error de conexión. Inténtalo otra vez.': 'Connection error. Try again.',
    'No se pudo cargar. Revisa tu internet.': 'Could not load. Check your internet.',
    'No se pudo cerrar. Inténtalo de nuevo.': 'We could not close it. Try again.',
    'No se pudo procesar. Intenta de nuevo.': 'We could not process it. Try again.',
    'Se descarga con el sello de Casa Pepe.': 'It downloads with the Casa Pepe stamp.',
    'Te quedas {n} noche más, hasta el {f}.': 'You stay {n} more night, until {f}.',
    'Tu reserva quedó preconfirmada por {p}': 'Your booking is pre-confirmed at {p}',
    'requiere mucho estudio · practica aquí': 'takes a lot of practice · train here',
    'Estás a {d}. Acércate a menos de {r} m.': 'You are {d} away. Get within {r} m.',
    'No hizo puntos, así que no suelta nada.': 'They scored nothing, so they give up nothing.',
    'No se pudo confirmar. Intenta de nuevo.': 'We could not confirm it. Try again.',
    'Sueltas los {n} puntos de esta partida.': 'You give up the {n} points from this round.',
    'Sé el primero en la tabla. ¡Juega otra!': 'Be the first on the board. Play another one!',
    'Te quedas {n} noches más, hasta el {f}.': 'You stay {n} more nights, until {f}.',
    ', ya cargado a la tarjeta de tu reserva.': ', already charged to the card on your booking.',
    'No disponible ahora. Inténtalo de nuevo.': 'Not available right now. Try again.',
    'No pudimos traer tu reserva ahora mismo.': 'We could not bring up your booking right now.',
    'Revisa tu internet e inténtalo de nuevo.': 'Check your internet and try again.',
    '{pts} puntos · {ok} de {total} correctas': '{pts} points · {ok} of {total} right',
    '. El cobro lo cuadra recepción al llegar.': '. Reception settles the payment when you arrive.',
    'Activa tu ubicación para aceptar el reto.': 'Turn on your location to take the challenge.',
    'El precio es por noche · {n} noches = {t}': 'The price is per night · {n} nights = {t}',
    'Aún no hay personajes activos. Muy pronto.': 'No characters are out there yet. Very soon.',
    'El personaje más cercano está a <b>{d}</b>': 'The closest character is <b>{d}</b> away',
    'Muy pronto podrás pedir piezas a tu cuarto.': 'Very soon you will be able to order pieces to your room.',
    '¡Tienes tu nueva habitación a un solo clic!': 'Your new room is one click away!',
    'Ahora mismo no podemos extender tu estancia.': 'We cannot extend your stay right now.',
    'Quiero pedir a mi cuarto: {pieza} ({precio})': 'I would like this brought to my room: {pieza} ({precio})',
    'Todavía no has comprado ninguna experiencia.': 'You have not booked an experience yet.',
    'Recepción lo termina y te confirma al llegar.': 'Reception finishes it and confirms when you arrive.',
    '⚔️ <b>Le ganaste a {rival}</b> {mis} a {sus}.': '⚔️ <b>You beat {rival}</b> {mis} to {sus}.',
    'Escribe cuánto quieres pagar de más por noche.': 'Enter how much extra you want to pay per night.',
    'Tu reserva, tus papeles y lo que has comprado.': 'Your booking, your paperwork and everything you have bought.',
    'Listo. Te avisamos aunque tengas APePe cerrada.': 'Done. We will let you know even with APePe closed.',
    'No pudimos apartarla. Pregúntanos en recepción.': 'We could not hold it. Ask us at reception.',
    'Tenemos dos redes — usa la que mejor te agarre.': 'We have two networks — use whichever has the better signal.',
    'Todavía estás lejos ({n} m). Acércate al lugar.': 'You are still far away ({n} m). Get closer to the spot.',
    'Vemos si puedes quedarte sin cambiarte de cama.': 'We are checking if you can stay without changing beds.',
    '🎯 <b>¡Estás en un lugar!</b> Tócame para retar.': '🎯 <b>You are on the spot!</b> Tap me to play.',
    'Muy pronto subimos las piezas de esta colección.': 'We are adding the pieces of this collection very soon.',
    'No hay preguntas ahora mismo. Intenta más tarde.': 'No questions right now. Try again later.',
    'Sube un poco tu propuesta e inténtalo de nuevo 🙂': 'Raise your offer a little and try again 🙂',
    '{a} de {t} correctas · {p}% de reloj aprovechado': '{a} of {t} right · {p}% of the clock used well',
    'Activa tu ubicación para saber si ya estás cerca.': 'Turn on your location to see if you are close.',
    'Va ganando {nombre} con {pts}. Tú llevas {n} hoy.': '{nombre} is in front with {pts}. You have {n} today.',
    'Vista previa: puedes retar sin estar en el lugar.': 'Preview mode: you can play without being at the spot.',
    '⚔️ Empate con {rival} a {mis}. Nadie suelta nada.': '⚔️ Tied with {rival} at {mis}. Nobody gives up anything.',
    'Nadie ha jugado hoy todavía. El premio está libre.': 'Nobody has played today yet. The prize is up for grabs.',
    'No pudimos leer tu ubicación. Actívala para jugar.': 'We could not read your location. Turn it on to play.',
    'No pudimos cargar tu pasaporte. Revisa tu internet.': 'We could not load your passport. Check your connection.',
    ', justo antes de la power hour. También te espera un': ', right before power hour. And there is a',
    'Check-in, tu cuarto, tus experiencias y tus boletos.': 'Check-in, your room, your experiences and your tickets.',
    'Por muy poquito. Vuelve a intentarlo en un momento 🙂': 'So close. Try again in a moment 🙂',
    'Puedes repetirlo cuando quieras para subir de carta.': 'Play again whenever you like to level up your card.',
    'Si necesitas cambiar algo, pregúntanos en recepción.': 'If you need to change anything, ask us at reception.',
    'Nadie ha desbloqueado cartas todavía. ¡Sé el primero!': 'Nobody has unlocked a card yet. Be the first!',
    'Va ganando {nombre} con {pts}. Nadie lo ha alcanzado.': '{nombre} is in front with {pts}. Nobody has caught up.',
    'No pudimos cargar tus opciones. Pregunta en recepción.': 'We could not load your options. Ask at reception.',
    'No pudimos ver tus opciones. Pregúntanos en recepción.': 'We could not check your options. Ask us at reception.',
    'Enséñale el código de abajo a quien esté en la terraza.': 'Show the code below to the terrace team.',
    '🏆 Ayer ganó <b>{nombre}</b> con {pts} puntos: {premio}.': '🏆 Yesterday <b>{nombre}</b> won with {pts} points: {premio}.',
    'Estamos cuadrando tu cama con recepción; te confirmamos.': 'We are sorting your bed out with reception; we will confirm.',
    'Sólo se puede mejorar la habitación una vez por reserva.': 'The room can only be upgraded once per booking.',
    'Aunque no tengas APePe abierta. Te pedirá permiso una vez.': 'Even when APePe is closed. It will ask your permission once.',
    'Estamos apartándola en el sistema. No cierres la pantalla.': 'We are holding it in the system. Do not close this screen.',
    'Las experiencias que has comprado. Cada boleto lleva su QR.': 'The experiences you have booked. Every ticket carries its QR.',
    'La liga vale diez minutos: si caduca, recarga esta pantalla.': 'The link lasts ten minutes: if it expires, reload this screen.',
    'No diste permiso. Los verás igual en la campanita de arriba.': 'You did not give permission. You will still see them in the bell up top.',
    'No pudimos ver tus opciones ahora. Pregúntanos en recepción.': 'We could not check your options right now. Ask us at reception.',
    'Tarifas directas, upgrades y lo que se nos ocurra regalarte.': 'Direct rates, upgrades and whatever else we feel like giving you.',
    'Este personaje todavía no tiene su reto listo. Vuelve pronto.': 'This character’s challenge is not ready yet. Come back soon.',
    'Entra con tu cuenta de Sincrético para ver lo que has comprado.': 'Sign in with your Sincrético account to see what you have booked.',
    'Aquí la sacaste en <b>{t}</b> {e}. Puedes repetirlo para subirla.': 'You won it here in <b>{t}</b> {e}. Play again to level it up.',
    'No acertaste ninguna. Vuelve a intentarlo: las preguntas cambian.': 'You did not get any right. Try again — the questions change.',
    'Suelta los {n} puntos de esa partida; los tuyos se quedan contigo.': 'They give up the {n} points from that round; yours stay with you.',
    '¿Cuánto pagarías <b>de más por noche</b> para subir a este cuarto?': 'How much would you pay <b>extra per night</b> to move up to this room?',
    'Ábrelo desde la liga de tu reserva, que es como sabemos quién eres.': 'Open this from your reservation link so we know who you are.',
    'Don José te orienta; para cambios en tu reserva, recepción confirma.': 'Don José points you the right way; for changes to your booking, the front desk confirms.',
    '🎁 <b>Pasaste los 500 puntos.</b> Te dejamos en la billetera {cartas}.': '🎁 <b>You passed 500 points.</b> We dropped {cartas} into your wallet.',
    'No pudimos comprobar tu check-in. Revisa tu internet y vuelve a entrar.': 'We could not check your check-in. Check your internet and come back in.',
    'No se pudo activar en este teléfono. Los verás en la campanita de arriba.': 'We could not turn it on for this phone. You will see them in the bell up top.',
    'Pídele la contraseña del WiFi a recepción; en un momento la tendrás aquí.': 'Ask reception for the WiFi password — it will show up here soon.',
    'Abre esta pantalla desde la liga de tu reserva para configurar tus avisos.': 'Open this screen from your booking link to set up your notifications.',
    'Aquí van a aparecer tus cartas. La primera llega cuando hagas el check-in.': 'Your cards will show up here. The first one arrives when you check in.',
    'Revísala y fírmala para aceptarla. En cuanto firmes, la habitación es tuya.': 'Check it and sign to accept. As soon as you sign, the room is yours.',
    'Todavía no hay nada firmado. Aparecerá aquí en cuanto termines el check-in.': 'Nothing signed yet. It shows up here as soon as you finish check-in.',
    'Por ahora no hay upgrades disponibles para tu reserva. ¡Ya estás muy bien! 🧡': 'No upgrades available for your booking right now. You are already in a good spot! 🧡',
    'Esa oferta se queda cortita 🙂 Sube un poco tu propuesta e inténtalo de nuevo.': 'That offer falls a little short 🙂 Raise it a bit and try again.',
    'Sobre todo si sales de las zonas turísticas, donde no siempre aceptan tarjeta.': 'Especially outside the touristy areas, where cards are not always accepted.',
    'Los puntos de los últimos siete días. El premio, en cambio, se reparte por día.': 'Points from the last seven days. The prize, though, is handed out every day.',
    '¿Listo para encontrar los secretos de esta ciudad? ¡No dejes que se te escapen!': 'Ready to find this city’s secrets? Do not let them get away.',
    'Los avisos son de esta reserva. Al terminar tu estancia dejamos de mandarte nada.': 'These notifications belong to this booking. When your stay ends we stop sending anything.',
    'Tu navegador no puede mandarte avisos. Los verás igual en la campanita de arriba.': 'Your browser cannot send you notifications. You will still see them in the bell up top.',
    'No pudimos cargar la red ahora mismo. Vuelve a intentarlo o pregunta en recepción.': 'We could not load the network right now. Try again or ask at reception.',
    'No pudimos cargar tus opciones ahora. Inténtalo más tarde o pregunta en recepción.': 'We could not load your options right now. Try again later or ask at reception.',
    '«Contéstame cinco preguntas sobre mi vida. Si me ganas, me quedo en tu pasaporte.»': '“Answer five questions about my life. Beat me and I am yours, in your passport.”',
    '✓ Contraseña copiada. Abre tus <b>ajustes de WiFi</b>, toca <b>{ssid}</b> y pégala.': '✓ Password copied. Open your <b>WiFi settings</b>, tap <b>{ssid}</b> and paste it.',
    'Los bloqueaste en este navegador. Actívalos desde los ajustes del sitio y vuelve aquí.': 'You blocked them in this browser. Turn them on in the site settings and come back here.',
    'Solo entras al PepeQuiz si tú quieres. Al terminar tu estancia te sacamos de la tabla.': 'You only join PepeQuiz if you want to. When your stay ends we take you off the board.',
    'Es un extra por noche, además de lo que ya pagaste. Se carga a la tarjeta de tu reserva.': 'It is an extra per night, on top of what you already paid. It is charged to the card on your booking.',
    'Abre tus <b>ajustes de WiFi</b> y toca <b>{ssid}</b>. Es red abierta, no pide contraseña.': 'Open your <b>WiFi settings</b> and tap <b>{ssid}</b>. It is an open network, no password.',
    'Aparece en {n} lugar(es). Ábrelo en el <b>mapa</b> y, cuando estés cerca, acepta su reto.': 'They show up in {n} place(s). Open the <b>map</b> and take their challenge once you are close.',
    'Es una manera estupenda de moverte, pero evita las horas pico y te será mucho más cómodo.': 'A fantastic way to get around — just plan around rush hours and it will be a much smoother ride.',
    'Todavía no tenemos listo el aviso al teléfono. Mientras, la campanita de arriba no falla.': 'Phone notifications are not ready yet. In the meantime, the bell up top never fails.',
    'Compra un paquete de Telcel en cualquier Oxxo o 7-Eleven. Es el que mejor cobertura tiene.': 'Get a Telcel data package at any Oxxo or 7-Eleven. It has the most reliable coverage.',
    'Es un extra sobre lo que ya pagaste: tu reserva no cambia. Escribe sólo la diferencia por noche': 'It is an extra on top of what you already paid: your booking does not change. Enter only the difference per night',
    'Aprender tiene premio. Reta a otros viajeros y gana el premio del día. ¿Qué tan mexicano eres ya?': 'Learning pays. Challenge other travellers and win today’s prize. How Mexican are you by now?',
    '⚔️ Retaste a <b>{rival}</b> con <b>{pts}</b> puntos. Se cierra cuando él juegue esa misma partida.': '⚔️ You challenged <b>{rival}</b> with <b>{pts}</b> points. It closes once they play that same round.',
    'Antes de llegar, sube de categoría — tú pones el precio. Lo que ofrezcas se suma a lo que ya pagaste.': 'Move up a category before you arrive — you name the price. Whatever you offer is added to what you already paid.',
    'Muy pronto verás aquí nuestro menú de La Cósmica. Mientras, pregúntale a Don José o pásate a la barra.': 'Our La Cósmica menu lands here very soon. Meanwhile, ask Don José or come up to the bar.',
    '¿SIM? ¿Museos? Descubre qué descuentos tiene Casa Pepe para ti. Los buenos turistas ya no pagan de más.': 'SIM card? Museums? See what Casa Pepe has lined up for you. Good travellers stop overpaying.',
    'Como reservaste por {f}, puedes pasarte a nuestra tarifa directa con <b>15% menos</b>. Sin penalización.': 'Since you booked through {f}, you can move to our direct rate and pay <b>15% less</b>. No penalty.',
    'Para jugar necesitamos saber cuál es tu reserva: entra con la liga que te mandamos por correo o WhatsApp.': 'To play we need to know which booking is yours: come in through the link we sent you by email or WhatsApp.',
    'Sube a una privada pagando sólo la diferencia del día — habitación solo para ti. No vuelves a pagar el cuarto.': 'Move up to a private room by paying just the difference for the day — a room only for you. You do not pay for the room again.',
    '¿La quieres? Toca «Pídela a tu cuarto» y Don José / recepción te la lleva. Se paga en recepción o al check-out.': 'Want it? Tap “Bring it to my room” and Don José or the front desk brings it up. You pay at the front desk or at check-out.',
    'Abre esta pantalla desde la liga de tu reserva —la que te mandamos por correo o WhatsApp— y aquí verás tus fechas.': 'Open this screen from your booking link — the one we sent you by email or WhatsApp — and your dates will show up here.',
    'El quinto piso: desayuno, comida y cena en el mismo sitio. Y es donde pasa todo — Power Hour, karaoke, DJ y eventos.': 'The fifth floor: breakfast, lunch and dinner in the same vibrant space. And it is where the action happens — Power Hour, karaoke nights, DJ sessions and events.',
    'Reta lo que sabes de México y de nuestros tours. Suma puntos y compite en la tabla. ¡Hasta puedes retar a los Pepes!': 'Test what you know about Mexico and about our tours. Rack up points and climb the board. You can even challenge the Pepes!',
    'No pude conectarme ahorita. Revisa tu internet e inténtalo otra vez; si es urgente, recepción está en el lobby las 24h.': 'I could not connect just now. Check your internet and try again; if it is urgent, the front desk is in the lobby 24h.',
    'Perdona, se me cruzaron los cables. Inténtalo de nuevo en un momento, o pásate a recepción — el lobby está abierto 24h.': 'Sorry, my wires got crossed. Try again in a moment, or come by the front desk — the lobby is open 24h.',
    'Al firmar acepto el cambio de habitación y autorizo el cargo del extra a la tarjeta que dejé como garantía en mi reserva.': 'By signing I accept the room change and I authorise the charge for the extra to the card I left as a guarantee on my booking.',
    'Para ver si puedes quedarte necesitamos saber cuál es tu reserva: entra con la liga que te mandamos por correo o WhatsApp.': 'To see if you can stay we need to know which booking is yours: use the link we sent you by email or WhatsApp.',
    '¿En tu propio teléfono? Toca <b>Conectarme</b>: te abrimos los ajustes de WiFi para elegir <b>{ssid}</b> (sin contraseña).': 'On your own phone? Tap <b>Connect</b> and we will open your WiFi settings so you can pick <b>{ssid}</b> — no password needed.',
    '<b>{rival}</b> te retó con <b>{pts}</b> puntos. Juegas sus mismas preguntas; el que pierde suelta los puntos de esa partida.': '<b>{rival}</b> challenged you with <b>{pts}</b> points. You play their same questions; whoever loses gives up the points from that round.',
    'Un coctel de cortesía de 14:00 a 19:00, un Café de Olla al llegar, un walking tour diario de 2 horas y el mapa de la ciudad.': 'A welcome cocktail from 2:00 to 7:00 PM, a Café de Olla when you arrive, a daily 2-hour walking tour and the city map.',
    'Cada pieza está hecha a mano por su gente. Lo que se venda es lo que recibe quien la hizo. Pídela y te la llevamos a tu cuarto.': 'Every piece is handmade by its own people. What it sells for is what the maker takes home. Order it and we bring it up to your room.',
    'Cada peso que un tour deja en la comunidad te vuelve como un Vnum. Todavía estamos decidiendo dónde se canjean: por ahora se guardan.': 'Every peso a tour leaves in the community comes back to you as a Vnum. We are still deciding where they can be spent: for now they just add up.',
    'Todavía no tienes Vnums. Se ganan con las experiencias de Sincrético: cada peso que el tour deja en la comunidad te vuelve como un Vnum.': 'No Vnums yet. You earn them with Sincrético experiences: every peso the tour leaves in the community comes back to you as a Vnum.',
    'Para trabajar o simplemente estar a gusto. Es de todos: puedes usarlo aunque todavía no hayas hecho check-in, o ya hayas hecho check-out.': 'Perfect for joining our digital nomad community or just sitting comfortably. Everyone is welcome, whether you have not checked in yet or already checked out.',
    '¿En tu propio teléfono? Toca <b>Conectarme</b>: te abrimos los ajustes de WiFi y te copiamos la contraseña para pegarla en <b>{ssid}</b>.': 'On your own phone? Tap <b>Connect</b> and we will open your WiFi settings and copy the password, ready to paste into <b>{ssid}</b>.',
    'Compartir regadera a veces se complica. Por eso hay regaderas y baños extra en el segundo piso: si la de tu cuarto está ocupada, usa esos.': 'Sharing a shower can be tricky. That is why there are extra showers and toilets on the second floor: if the one in your room is taken, use those.',
    'En el segundo piso, sigue el camino y ahí está el equipo, a cualquier hora. Dudas, ayuda o recomendaciones para tu estancia: para eso estamos.': 'On the second floor, follow the path and you will find our host team working around the clock. Questions, help or suggestions — that is what we are here for.',
    'El QR sólo vive aquí, en la app: por eso no se puede copiar ni cobrar dos veces. Quien lo cobra es el equipo de terraza, desde su propio celular.': 'The QR only lives here, in the app — that is why it cannot be copied or redeemed twice. The terrace team redeems it from their own phone.',
    'El premio de hoy es para quien acabe arriba de esta tabla. Retas con los puntos de esta ronda: {pts}; el que pierde suelta los puntos de esa partida.': 'Today\'s prize goes to whoever finishes top of this board. You challenge with this round\'s points: {pts}; whoever loses gives up the points from that round.',
    'En la planta baja, junto al elevador, tienes un cuarto de maletas sin costo. Lo cuida nuestro guardia, que está las 24 horas: tus cosas están seguras.': 'On the ground floor next to the elevator there is a complimentary storage room. It is under the watchful care of our 24/7 on-site guard, so your belongings are safe.',
    '¿Quieres ahorrar o comer algo de casa? La cocina común está equipada con microondas, estufa, refri y lo necesario para cocinar. Marca tus cosas y tu comida.': 'Want to save money or cook a homemade meal? The common kitchen is fully equipped with a microwave, stove, fridge and the essentials. Feel free to mark your things and your food.',
    'El PepeQuiz es para huéspedes con check-in hecho. <a href="{liga}" style="color:var(--naranja);text-decoration:underline">Haz tu check-in</a> y vuelve: tu nombre entra solo.': 'PepeQuiz is for guests who have checked in. <a href="{liga}" style="color:var(--naranja);text-decoration:underline">Do your check-in</a> and come back: your name fills itself in.',
    'Casa Pepe es un hotel con espíritu de hostal, donde lo que de verdad importa es que los viajeros se conozcan. Estás a dos calles del Zócalo, en el corazón del Centro Histórico.': 'Casa Pepe is a hotel with the spirit of a hostel, where connecting travelers truly matters. You are two blocks from the Zócalo, right in the heart of the Historic Center.',
    'Uno de los mejores rincones de la casa para una foto. Conéctate a la smart TV, échale un ojo a nuestros libros de viaje por México, o come tranquilo si buscas un rato de calma.': 'One of our top hotspots for a memorable photo. Connect to the smart TV, browse our book collection for travel inspiration in Mexico, or have a quiet lunch.',
    '¡Qué gusto tenerte por aquí! Soy Don José, el conserje de la casa. Pregúntame lo que necesites de tu estancia: cómo llegar, horarios, qué hacer en la ciudad, o cualquier duda con tu reserva. 🎩': 'So glad to have you here! I am Don José, the concierge of the house. Ask me anything about your stay: how to get around, opening hours, what to do in the city, or any question about your booking. 🎩',
    'El Metrobús (los rojos) es lo más barato: la tarjeta cuesta unos $15 y te bajas en Isabel la Católica, o en Zócalo si vas en metro. Con maletas o de noche, taxi autorizado (~$500) o Uber/DiDi (~$200).': 'The Metrobús (the red buses) is the cheapest: the travel card is about $15 MXN and you get off at Isabel la Católica, or Zócalo if you take the Metro. With luggage or late at night, an authorized taxi (~$500 MXN) or Uber/DiDi (~$200 MXN).',
    'Cada pregunta tiene su reloj. Entre más rápido y mejor le atines, mejor la carta: madera, pixel wixáxika, oro o día de muertos. Puedes volver a intentarlo las veces que quieras, y las preguntas cambian.': 'Every question is on the clock. The faster and sharper you are, the better the card: wood, pixel wixáxika, gold or día de muertos. Play as many times as you like — the questions change.',
    '⚔️ Retaste a <b>{rival}</b> con {pts} puntos. Le sale el reto al abrir su PepeQuiz, y el duelo no se cierra hasta que él juegue esa misma partida. Si pierde, suelta los puntos que haga; los tuyos se quedan contigo.': '⚔️ You challenged <b>{rival}</b> with {pts} points. They see it when they open their PepeQuiz, and the duel stays open until they play that same round. If they lose, they give up whatever they score; yours stay with you.',

    /* Pepe GO! — la invitación del pasaporte y las tres épocas. Son textos de
       Javi: no se traducen palabra por palabra, se traduce el tono. El primo
       del oro y el primo de la sangre se quedan, que es donde está la gracia. */
    'Todo el que pasa por esta tierra deja algo en ella que nos vuelve más mexicanos.': 'Everyone who passes through this land leaves something behind that makes us more Mexican.',
    'Tú eres uno de esos viajeros que pasa por la región más transparente del aire sin saber que lo que dejas puede ser más grande que lo que te llevas.': 'You are one of those travelers crossing the most transparent region of the air, with no idea that what you leave here may be greater than what you take with you.',
    'La Ciudad de México está llena de anécdotas de las personas que la caminaron en los últimos 700 años.': 'Mexico City is full of the stories of the people who have walked it over the last 700 years.',
    'Tú eres uno de esos viajeros que cruza la Angelópolis sin saber que lo que dejas puede ser más grande que lo que te llevas.': 'You are one of those travelers crossing the Angelópolis, with no idea that what you leave here may be greater than what you take with you.',
    'Puebla está llena de anécdotas de quienes la caminaron: de Cholula a los fuertes, de la Talavera al mole.': 'Puebla is full of the stories of those who walked it: from Cholula to the forts, from Talavera to mole.',
    '¿Te atreves a llevártelas contigo?': 'Care to take them with you?',
    'Acércate al lugar donde hay una carta escondida —el pin empieza a latir cuando ya estás dentro—, responde el test y llévate la carta de la Lotería contigo.': 'Get close to a place where a card is hidden — the pin starts beating once you are within range — answer the quiz and the Lotería card is yours.',

    'Aquí ya había ciudad, calendario y dioses cuando en Europa todavía se discutía si el mundo se acababa en el mar. Una isla en un lago, tres calzadas y un mercado que dejó mudos a los que solo habían visto Venecia. La Gran Tenochtitlán fue la capital del Imperio que aún se come, se admira, se viste y se habla desde la identidad mexicana.': 'There was already a city here, and a calendar, and gods, while Europe was still arguing whether the world ended out at sea. An island on a lake, three causeways, and a market that left men who had only seen Venice speechless. Gran Tenochtitlán was the capital of an empire that is still eaten, still admired, still worn and still spoken from inside Mexican identity.',
    'El Encuentro, 1519. Uno de los diez momentos que más cambiaron la historia universal, y no por la guerra sino por lo que nació de él: dos mundos volviéndose uno. Como en todas las familias siempre hay un primo al que le gusta el oro y otro al que le gusta la sangre, claro, pero lo que quedó fue la mezcla de lo que los viajeros y los anfitriones pueden lograr: la virgen sobre el cerro de otra diosa, la talavera con azul de China, el español con el náhuatl adentro o años después el kebab convertido en taco al pastor o el luto de la muerte pintado de colores.': 'The Encounter, 1519. One of the ten moments that changed world history the most — not for the war, but for what was born of it: two worlds becoming one. As in every family there is always one cousin who likes gold and another who likes blood, of course, but what lasted was the blend that travelers and hosts can make together: the virgin standing on another goddess’s hill, Talavera painted with blue from China, Spanish with Náhuatl inside it, and, centuries on, the kebab turned into taco al pastor, or the mourning of death painted in colors.',
    '1821. México se suelta de las coronas europeas y empieza una pelea que no era sólo suya: la soberanía de todo un continente. De ahí salen los murales, la escuela para todos y la idea de que una nación se construye enseñándola. «Por mi raza hablará el espíritu», escribió Vasconcelos, y lo mandó grabar en el escudo de la Universidad. Estas cartas son los últimos dos siglos.': '1821. Mexico breaks free of the European crowns and begins a fight that was never only its own: the sovereignty of an entire continent. Out of it came the murals, schooling for everyone, and the idea that a nation is built by teaching it. «The spirit shall speak through my race», wrote Vasconcelos, and had it carved into the University’s coat of arms. These cards are the last two centuries.',

    'Antes que cualquier reino de Europa, aquí ya se rezaba. Cholula es de las ciudades vivas más antiguas de América, y su Gran Pirámide —Tlachihualtépetl, «el cerro hecho a mano»— es, por volumen, la más grande del planeta: una montaña de adobe dedicada a Quetzalcóatl sobre la que los siglos apilaron dioses. Estas cartas son lo que ya estaba aquí antes de que llegara nadie.': 'Long before any kingdom in Europe, people were already praying here. Cholula is among the oldest living cities in the Americas, and its Great Pyramid — Tlachihualtépetl, «the hill made by hand» — is, by volume, the largest on the planet: a mountain of adobe raised to Quetzalcóatl, on which the centuries went on stacking gods. These cards are what was already here before anyone arrived.',
    'Puebla no se levantó encima de nadie: se trazó desde cero en 1531, la Puebla de los Ángeles, la primera ciudad pensada para el encuentro de dos mundos. De ahí salió la mezcla que la hace única: la Talavera con el azul que venía de China, los azulejos, la Biblioteca Palafoxiana, el mole y la china poblana. Dos mundos volviéndose uno, en cada fachada.': 'Puebla was not built on top of anyone: it was drawn from scratch in 1531 — Puebla de los Ángeles, the first city designed for the meeting of two worlds. From that came the blend that makes it unlike anywhere else: Talavera with blue that came from China, the tiled façades, the Palafoxiana Library, mole, and the china poblana. Two worlds becoming one, on every front wall.',
    'De la Independencia para acá, Puebla le puso nombres y batallas a la nación: el 5 de mayo de 1862 y los poblanos que la caminaron después. Estas cartas son los símbolos y las personas de los últimos dos siglos.': 'From Independence onward, Puebla gave the nation names and battles: the fifth of May, 1862, and the poblanos who walked the city afterwards. These cards are the symbols and the people of the last two centuries.',
    'Edición especial. El 5 de mayo de 1862, en los cerros de Loreto y Guadalupe, un ejército peor armado le ganó al mejor del mundo. Aquí están los que hicieron esa mañana: Zaragoza, los fuertes, los serranos de la sierra y el telegrama que se volvió leyenda.': 'Special edition. On the fifth of May, 1862, on the hills of Loreto and Guadalupe, a worse-armed army beat the best in the world. Here are the ones who made that morning: Zaragoza, the forts, the highlanders from the sierra, and the telegram that turned into legend.'
  };

  var LANG = lee();
  try { document.documentElement.lang = LANG; } catch (_) {}
  function t(f) {
    if (LANG !== 'en') return f;
    var k = String(f == null ? '' : f).trim();
    return Object.prototype.hasOwnProperty.call(DIC, k) ? DIC[k] : f;
  }
  /* Barre el HTML fijo. `data-i18n` sin valor usa el propio texto como llave,
     así no se escribe la frase dos veces. */
  function barre(raiz) {
    var r = raiz || document;
    Array.prototype.forEach.call(r.querySelectorAll('[data-i18n]'), function (e) {
      var k = e.getAttribute('data-i18n') || e.textContent;
      var v = t(k); if (v !== k || e.getAttribute('data-i18n')) e.textContent = v;
    });
    Array.prototype.forEach.call(r.querySelectorAll('[data-i18n-ph]'), function (e) {
      e.placeholder = t(e.getAttribute('data-i18n-ph') || e.placeholder);
    });
    Array.prototype.forEach.call(r.querySelectorAll('[data-i18n-aria]'), function (e) {
      e.setAttribute('aria-label', t(e.getAttribute('data-i18n-aria')));
    });
  }
  window.apepeT = t;
  window.apepeBarre = barre;
  window.apepeLang = function () { return LANG; };

  function estilo() {
    if (document.getElementById('apLangCss')) return;
    var c = document.createElement('style');
    c.id = 'apLangCss';
    c.textContent = [
      '.apLang{display:inline-flex;align-items:center;border:0;padding:0;overflow:hidden;',
      '  border-radius:999px;background:rgba(255,255,255,.18);height:38px;font-family:inherit;cursor:pointer}',
      '.apLang b{display:block;padding:0 10px;line-height:38px;font-size:12px;font-weight:700;',
      '  letter-spacing:.04em;color:rgba(255,255,255,.72)}',
      '.apLang b.on{background:#fff;color:#1E1A16}',
      '@media(prefers-reduced-motion:no-preference){.apLang b{transition:background .15s}}'
    ].join('');
    document.head.appendChild(c);
  }

  function monta() {
    var top = document.querySelector('header.top .in .dcha') ||
              document.querySelector('header.top .in') ||
              document.querySelector('header.top');
    if (!top || document.querySelector('.apLang')) return !!top;
    estilo();
    var l = lee();
    try { document.documentElement.lang = l; } catch (_) {}
    var b = document.createElement('button');
    b.className = 'apLang';
    b.type = 'button';
    b.setAttribute('aria-label', l === 'en' ? 'Change language' : 'Cambiar idioma');
    b.innerHTML = '<b class="' + (l === 'es' ? 'on' : '') + '">ES</b>' +
                  '<b class="' + (l === 'en' ? 'on' : '') + '">EN</b>';
    /* La campanita se mete como primer hijo, así que el idioma queda a su
       derecha sin que importe cuál de los dos scripts cargue antes. */
    b.onclick = function () { pon(l === 'es' ? 'en' : 'es'); };
    top.appendChild(b);
    return true;
  }

  function arranca() {
    monta();
    try { barre(); } catch (_) {}
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', arranca);
  } else { arranca(); }
  /* La campanita y los carruseles llegan tarde: se vuelve a barrer un par de
     veces en vez de encadenarse a cada script. */
  var n = 0;
  var reloj = setInterval(function () {
    monta(); try { barre(); } catch (_) {}
    if (++n > 12) clearInterval(reloj);
  }, 400);
})();
